### ISSUE TITLE
Cannot import value from node_modules

### ISSUE THREAD

**Issue by andrey-skl** [princed/postcss-modules-values-replace#12]
If i use `@value unit, link-color from 'some-module/global.css';`, it resolves this path to `current_directory/some-module/global.css`

**Comment by princed** [comment]
[Ring UI generator](https://github.com/JetBrains/ring-ui/tree/master/packages/generator) seems to be working fine 😉 
Please do let me know if there's some reproducible test-case.

**Comment by CloudPower97** [comment]
@huston007 Did you manage to solve this issue?
@princed I've the same exact problem.

**Comment by princed** [comment]
@CloudPower97 It's probably some kind of configuration problem. Are you able to produce a minimal test case?
