### ISSUE TITLE
Ignore unused values to boost performance

### ISSUE THREAD

**Issue by khanguy00** [princed/postcss-modules-values-replace#32]
### The problem

Take a look at this example:

```
// main.css
@value sidebarColor from 'sidebar.css';
.sidebar {
  background: sidebarColor;
}

// sidebar.css
@value themeColor from 'theme.css';
@value sidebarColor: #00ff00;

// theme.css
@value themeColor: #f1f1f1;
```

When resolving `main.css`, the plugin should only look for `sidebarColor` in `sidebar.css` and shouldn't aware of `themeColor`, because nothing in `main.css` uses `themeColor`. It's just wasting resource to resolve `theme.css` for nothing.

### Suggestion

Before walking into an imported file, the plugin should have a list of required definitions, then only looking for that list, nothing else.

I think I can work on this but I need your opinion on it first. WDYT?

**Comment by princed** [comment]
Hey Kha! 

Sure, great idea, I'd be happy to accept a PR.
