### ISSUE TITLE
Export regexes as the rules to reuse by other tools

### ISSUE THREAD

**Issue by khanguy00** [princed/postcss-modules-values-replace#35]
Hi, me again.

Can we expose these regexes?

https://github.com/princed/postcss-modules-values-replace/blob/5627d68f33dc980a8b48684c629f3a3e4aff903e/index.js#L9-L12

I think it will be helpful if other tools could reuse those patterns of `@value` for their purpose (for example validating postcss rules, or preprocess the file before this values-replace plugin).

**Comment by princed** [comment]
Hi Kha! What are actually trying to do? 😄

**Comment by khanguy00** [comment]
Well, you may know that in my project (and you still remember what is that project, right?), we have a stylelint plugin to block people from using some CSS properties and transform properties. To do that, I have to parse the CSS in a specific way, which then along with #33 will boost the processing speed further. Which mean that I should reuse the regexes.

Currently, I just copy them into my internal plugin, but I wonder if you could expose those regexes from your plugin?

**Comment by princed** [comment]
Oh I see. To be honest I'm not sure if exposing such implementation details is a good idea as I wouldn't like to provide any compatibility guarantees for them. Also I should say I copied most of them myself from https://github.com/css-modules/postcss-modules-values/blob/master/src/index.js#L5-L7

To sum up I think it'd be better to copy them over just as you did already. If it helps in any way, this plugin also provides a list of extracted values via postcss messages — https://github.com/princed/postcss-modules-values-replace#extracting-values-for-programmatic-use.

**Comment by khanguy00** [comment]
Fair point. Then I just keep the copied one. Thanks anyway.
