### ISSUE TITLE
Why does this module depend on node >= 6.5?

### ISSUE THREAD

**Issue by kumarharsh** [princed/postcss-modules-values-replace#4]
As far as I can see, the `postcss-modules-values` doesn't need any node engine version. Is there a reason why node version is required for this plugin? I'm using this with nodejs 5.12.0, and it compiles just fine. Can this engine dependency be removed?

**Comment by princed** [comment]
Yep, you're quite right. Published as 1.1.1

**Comment by rschamp** [comment]
This module does not work with Node 4, so I believe some engine warning is warranted. It would be nice if this would work with Node 4+ though, since it is still in LTS.
